# 1. How to build gconcord python package

### Step 1: Prepare for the following files:

 - core.cpp, core.h
 - wrap.cpp, wrap.h
 
### Step 2: Run the following command in the terminal to generate a shared library.

In [1]:
# g++ -fPIC -I/home/jovyan/Supportpkgs/eigen-3.37/ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"build/core.d" -MT"build/core.o" -o "build/core.o" "src/core.cpp"
# g++ -fPIC -I/home/jovyan/Supportpkgs/eigen-3.37/ -I/opt/conda/pkgs/python-3.7.3-h5b0a415_0/include/python3.7m/ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"build/wrap.d" -MT"build/wrap.o" -o "build/wrap.o" "src/wrap.cpp"
# g++ -shared -o "gconcord/sharedlib.so"  build/core.o build/wrap.o
# python setup.py install
# python


Make sure that the header includes:
 - #include <Eigen/Core>
 - #include <Eigen/Dense>
 - #include <Eigen/Sparse>

### Step 3: Write \_\_init\_\_.py file and gconcord.py file

### Step 4: Write setup.py file

### Step 5: Run setup.py file to install the package in the shell: python setup.py install.

### Step 6: Run python unittest/unittestGraphicalconcordModule.py for unit tests.

### Step 7 (Optional): Pack the files by *zip -r my_arch.zip my_folder* or *tar -cvzf my_arch.tar.gz my_folder*.

# 2. A demo for graphical_concord_ module

In [2]:
import numpy as np

x = np.array([[-0.57299987, -1.22881728,  0.24802264,  0.59779037,  0.65240208, 0.89373708],
              [ 0.84087632, -0.3383771 ,  0.0794175 ,  0.12716686, -0.97403288,-0.30804861],
              [ 0.13180135, -0.35350249,  0.01601294,  0.30258641,  0.19927309, 0.95847883],
              [ 0.44658609,  0.12839939, -2.36179304, -3.2224078 , -0.92297796,-1.55831917],
              [-1.00001779, -0.08302829,  0.6814525 ,  0.31812938, -0.50994963,-0.39614266],
              [-0.3653738 , -0.20899641,  0.33488842,  0.93276311,  0.18263188,-1.58771894],
              [ 0.53065032, -0.61604128, -0.67789621,  0.48183976,  0.20767173, 0.20307444],
              [-0.13368724, -0.12181896, -0.52881865, -0.91883273, -0.35672818,-0.09414685],
              [-1.23926047, -0.02615426, -1.02995135, -0.99250009, -0.89672846,-0.54350656],
              [-0.97725987, -0.95743644, -0.47911092, -0.22157924,  1.8751929 , 1.04114063],
              [ 1.4149165 ,  0.93326499, -0.09200369,  0.03342898,  1.71023076, 1.82671778],
              [ 0.19710653, -0.94066402, -1.15043928,  0.88932662,  0.3247554 ,-0.87942537]])   

In [3]:
# original version ccista
from gconcord.graphical_concord_ import GraphicalConcord, GraphicalConcordCV

model = GraphicalConcord(lam1 = 0.05, lam2 = 0, method='ista', steptype=1, maxit=10)
ans = model.fit(x)
ans.omega.round(6)

array([[ 1.743033, -1.062637,  0.51742 , -0.307406,  0.      , -0.229791],
       [-1.062637,  3.627425, -0.780665,  0.934706,  0.031817,  0.      ],
       [ 0.51742 , -0.780665,  2.372336, -1.277912,  0.242261, -0.446568],
       [-0.307406,  0.934706, -1.277912,  1.333334, -0.322365,  0.12464 ],
       [ 0.      ,  0.031817,  0.242261, -0.322365,  1.579282, -0.905498],
       [-0.229791,  0.      , -0.446568,  0.12464 , -0.905498,  1.286271]])

In [ ]:
from gconcord.graphical_concord_ import GraphicalConcord, GraphicalConcordCV

model = GraphicalConcord(lam1 = 0.05, lam2 = 0, method='ista')
ans = model.fit(x)
ans.omega.round(6)

array([[ 1.83353 , -1.210113,  0.716702, -0.449735,  0.028394, -0.246755],
       [-1.26438 ,  3.906002, -1.137168,  1.061136,  0.      ,  0.      ],
       [ 0.807525, -1.308349,  2.69425 , -1.52174 ,  0.461153, -0.636157],
       [-0.511333,  1.35707 , -1.59963 ,  1.479696, -0.48303 ,  0.258206],
       [ 0.      ,  0.      ,  0.4842  , -0.439442,  1.655126, -0.978652],
       [-0.274699,  0.01884 , -0.643809,  0.280404, -0.982891,  1.343092]])

In [ ]:
from gconcord.graphical_concord_ import GraphicalConcord, GraphicalConcordCV

model = GraphicalConcord(lam1 = 0.05, lam2 = 0, method='ista', steptype=1, maxit=100)
ans = model.fit(x)
ans.omega.round(6)

array([[ 1.833542, -1.210109,  0.716698, -0.449734,  0.028392, -0.246754],
       [-1.264418,  3.905998, -1.137159,  1.061136,  0.      ,  0.      ],
       [ 0.807577, -1.308339,  2.694238, -1.521741,  0.461143, -0.636153],
       [-0.511373,  1.357063, -1.599625,  1.479691, -0.483025,  0.2582  ],
       [ 0.      ,  0.      ,  0.484191, -0.439442,  1.655122, -0.978651],
       [-0.274704,  0.018838, -0.643805,  0.2804  , -0.982889,  1.343088]])

In [5]:
%%time

# true Omega
Omega = np.genfromtxt('Omega.txt', delimiter=',')

# Gaussian data
Xs = []
for i in range(15):
    X = np.genfromtxt('X_' + str(i+1) + '.txt', delimiter=',')
    Xs.append(X)

# graphical concord (unsymmetrized)
X_Omega_hat_cce = []

for i in range(len(Xs)):
    print(i)
    S = np.cov(Xs[i], rowvar=False)
    S.flat[::S.shape[0] + 1] = 0
    lam_max = np.max(np.abs(S))
    lam_min = 0.1 * lam_max
    lams = np.logspace(np.log10(lam_min), np.log10(lam_max), 10)
    # if i < 5:
    #     lams = np.logspace(np.log10(lam_min), np.log10(lam_max), 10)
    #     lam_min = lams[4]
    #     lams = np.logspace(np.log10(lam_min), np.log10(lam_max), 10)
    # elif i < 10:
    #     lams = np.logspace(np.log10(lam_min), np.log10(lam_max), 10)
    #     lam_min = lams[2]
    #     lams = np.logspace(np.log10(lam_min), np.log10(lam_max), 10)
    # else:
    #     lams = np.logspace(np.log10(lam_min), np.log10(lam_max), 10)
    for lam in lams:
        print(lam)
        concord = GraphicalConcord(lam1=lam, lam2=0, method='ista', maxit=500, assume_centered=True, assume_scaled=True).fit(Xs[i])
        
        X_Omega_hat = concord.omega
        X_Omega_hat_scaled = .5*(np.diag(np.diag(X_Omega_hat)) @ X_Omega_hat) + .5*(X_Omega_hat.T @ np.diag(np.diag(X_Omega_hat)))
        X_Omega_hat_cce.append(X_Omega_hat_scaled)

for i in range(len(X_Omega_hat_cce)):
    filename = 'X_Omega_hat_cce_' + str(i+1) + '.txt'
    np.savetxt(filename, X_Omega_hat_cce[i], fmt='%s', delimiter=',')

0
0.058846640358317284
0.07600335864203604
0.09816211239412774
0.12678124337978902
0.163744272417337
0.21148386018871748
0.2731419087827926
0.3527763407899417
0.45562816477242574
0.5884664035831727
1
0.059741463725905955
0.07715906746269269
0.09965476773430153
0.12870908188437322
0.1662341715921355
0.21469968863384933
0.27729531093384796
0.3581406659468093
0.4625564571318091
0.5974146372590595
2
0.06306838857877942
0.0814559561419511
0.10520441286860399
0.135876724198533
0.1754915376219351
0.22665603662855718
0.29273752818121423
0.37808505645973234
0.4883156280177008
0.6306838857877943
3
0.05776283581645619
0.07460357124905374
0.09635421745562935
0.12444625727758936
0.16072852189922662
0.2075888686172836
0.26811133372347135
0.3462791032572431
0.4472366598135467
0.5776283581645619
4
0.0636143421792704
0.08216108233177889
0.1061151183628693
0.1370529455745786
0.1770106859461501
0.228618092137805
0.2952716203169239
0.38135796230872493
0.4925427484705925
0.6361434217927039
5
0.040001765265

In [11]:
%%time

# true Omega
Omega = np.genfromtxt('Omega.txt', delimiter=',')

# Gaussian data
Ts = []
for i in range(15):
    T = np.genfromtxt('T_' + str(i+1) + '.txt', delimiter=',')
    Ts.append(T)

# graphical concord (unsymmetrized)
T_Omega_hat_cce = []

for i in range(len(Ts)):
    print(i)
    S = np.cov(Ts[i], rowvar=False)
    S.flat[::S.shape[0] + 1] = 0
    lam_max = np.max(np.abs(S))
    lam_min = 0.1 * lam_max
    lams = np.logspace(np.log10(lam_min), np.log10(lam_max), 10)

    for lam in lams:
        concord = GraphicalConcord(lam1=lam, lam2=0, method='ista', maxit=500, assume_centered=True, assume_scaled=True).fit(Ts[i])
        
        T_Omega_hat = concord.omega
        T_Omega_hat_scaled = .5*(np.diag(np.diag(T_Omega_hat)) @ T_Omega_hat) + .5*(T_Omega_hat.T @ np.diag(np.diag(T_Omega_hat)))
        T_Omega_hat_cce.append(T_Omega_hat_scaled)

for i in range(len(T_Omega_hat_cce)):
    filename = 'T_Omega_hat_cce_' + str(i+1) + '.txt'
    np.savetxt(filename, T_Omega_hat_cce[i], fmt='%s', delimiter=',')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
CPU times: user 15h 9min 39s, sys: 1min, total: 15h 10min 40s
Wall time: 15h 9min 26s


In [12]:
# re-run this!!
for i in range(10,50):
    filename = 'T_Omega_hat_cce_' + str(i+1) + '.txt'
    np.savetxt(filename, T_Omega_hat_cce[i-10], fmt='%s', delimiter=',')

In [6]:
%%time

# true Omega
Omega = np.genfromtxt('Omega.txt', delimiter=',')

# Gaussian data
Ts = []
for i in range(15):
    T = np.genfromtxt('T_' + str(i+1) + '.txt', delimiter=',')
    Ts.append(T)

# graphical concorde
T_Omega_hat_cce = []

for i in range(len(Ts)):
    print(i)
    S = np.cov(Ts[i], rowvar=False)
    S.flat[::S.shape[0] + 1] = 0
    lam_max = np.max(np.abs(S))
    lam_min = 0.025 * lam_max
    if i < 5:
        lams = np.logspace(np.log10(lam_min), np.log10(lam_max), 10)
        lam_min = lams[4]
        lams = np.logspace(np.log10(lam_min), np.log10(lam_max), 10)
    elif i < 10:
        lams = np.logspace(np.log10(lam_min), np.log10(lam_max), 10)
        lam_min = lams[3]
        lams = np.logspace(np.log10(lam_min), np.log10(lam_max), 10)
    else:
        lams = np.logspace(np.log10(lam_min), np.log10(lam_max), 10)
    for lam in lams:
        print(lam)
        concord = GraphicalConcord(lam1=lam, lam2=0, method='ista', maxit=500, assume_centered=True, assume_scaled=True).fit(Ts[i])
        
        T_Omega_hat = concord.omega
        T_Omega_hat_scaled = .5*(np.diag(np.diag(T_Omega_hat)) @ T_Omega_hat) + .5*(T_Omega_hat.T @ np.diag(np.diag(T_Omega_hat)))
        T_Omega_hat_cce.append(T_Omega_hat_scaled)

for i in range(len(T_Omega_hat_cce)):
    filename = 'T_Omega_hat_cce_' + str(i+1) + '.txt'
    np.savetxt(filename, T_Omega_hat_cce[i], fmt='%s', delimiter=',')

0
0.09375505907506602
0.11773004333058724
0.14783589535711877
0.18564039677341004
0.2331122413196088
0.2927235558507223
0.3675786379335161
0.46157561414005877
0.5796094374975814
0.7278267953174931
1
0.11397731390077984
0.14312352033716963
0.17972297620153038
0.2256816217113921
0.28339278290813325
0.355861805650798
0.44686256093578125
0.5611339716576212
0.7046267950684425
0.8848135122914393
2
0.12279225227968835
0.15419260916867944
0.19362264540999813
0.2431357055159101
0.3053102139553085
0.3833839482672633
0.48142264841002386
0.6045317427858307
0.7591222167105348
0.9532444685996778
3
0.1107770915308132
0.1391049391320527
0.17467676595886925
0.21934499778533728
0.2754357615298333
0.34587001981127746
0.4343156819572842
0.5453786127428624
0.6848424857626546
0.8599699719554319
4
0.11752351811702517
0.1475765576469046
0.1853147413883889
0.23270330954603188
0.29221005230331454
0.36693382158458376
0.4607659057632629
0.5785926710081166
0.7265500219460856
0.9123429328444647
5
0.0440253475650475

In [5]:
X = np.genfromtxt('X_10k.txt', delimiter=',')

In [6]:
lams

array([0.05923754, 0.07438573, 0.0934076 , 0.11729373, 0.14728801,
       0.18495241, 0.23224832, 0.29163871, 0.36621638, 0.45986501])

In [7]:
concord = GraphicalConcord(lam1=0.30969436, lam2=0, method='ista', maxit=100, steptype=1, assume_centered=True, assume_scaled=True).fit(X)
X_Omega_hat = concord.omega
filename = 'X_Omega_hat_sym_test1.txt'
np.savetxt(filename, X_Omega_hat, fmt='%s', delimiter=',')
concord = GraphicalConcord(lam1=0.20555433, lam2=0, method='ista', maxit=100, steptype=1, assume_centered=True, assume_scaled=True).fit(X)
X_Omega_hat = concord.omega
filename = 'X_Omega_hat_sym_test2.txt'
np.savetxt(filename, X_Omega_hat, fmt='%s', delimiter=',')
concord = GraphicalConcord(lam1=0.13643317, lam2=0, method='ista', maxit=100, steptype=1, assume_centered=True, assume_scaled=True).fit(X)
X_Omega_hat = concord.omega
filename = 'X_Omega_hat_sym_test3.txt'
np.savetxt(filename, X_Omega_hat, fmt='%s', delimiter=',')


In [15]:
%%time

# Gaussian data
X = np.genfromtxt('X_1.txt', delimiter=',')

# graphical concord (unsymmetrized)
X_Omega_hat_cc_unsym = []
lams = np.genfromtxt('X_lams.txt', delimiter=',')

for lam in lams:
    print(lam)
    concord = GraphicalConcord(lam1=lam, lam2=0, method='ista', maxit=100, steptype=1, assume_centered=True, assume_scaled=True).fit(X)
    X_Omega_hat = concord.omega
    X_Omega_hat_cc_unsym.append(X_Omega_hat)

for i in range(len(X_Omega_hat_cc_unsym)):
    filename = 'X_Omega_hat_cc_unsym_' + str(i+1) + '.txt'
    np.savetxt(filename, X_Omega_hat_cc_unsym[i], fmt='%s', delimiter=',')

0.05923754
0.07438572652291023


In [ ]:
%%time

# T-Dist. data
T = np.genfromtxt('T_1.txt', delimiter=',')

# graphical concord (unsymmetrized)
T_Omega_hat_cc_unsym = []
lams = np.genfromtxt('T_lams.txt', delimiter=',')

for lam in lams:
    print(lam)
    concord = GraphicalConcord(lam1=lam, lam2=0, method='ista', maxit=100, steptype=1, assume_centered=True, assume_scaled=True).fit(T)
    T_Omega_hat = concord.omega
    T_Omega_hat_cc_unsym.append(T_Omega_hat)

for i in range(len(T_Omega_hat_cc_unsym)):
    filename = 'T_Omega_hat_cc_unsym_' + str(i+1) + '.txt'
    np.savetxt(filename, T_Omega_hat_cc_unsym[i], fmt='%s', delimiter=',')

0.05923754


In [4]:
ans.lam1

0.2

In [5]:
ans.lam2

0.05